module.exports = {
  rules: {
    "no-console": ["off"],
    "array-element-newline": ["off"],
    "arrow-body-style": ["off"],
    "func-names": ["off"],
    "func-style": ["off"],
    "id-blacklist": ["off"],
    "id-length": ["off"],
    "id-match": ["off"],
    "init-declarations": ["off"],
    "line-comment-position": ["off"],
    "lines-around-comment": ["off"],
    "lines-between-class-members": ["off"],
    "max-classes-per-file": ["off"],
    "max-depth": ["off"],
    "max-lines-per-function": ["off"],
    "max-lines": ["off"],
    "max-params": ["off"],
    "max-statements": ["off"],
    "max-statements-per-line": ["off"],
    "multiline-comment-style": ["off"],
    "newline-per-chained-call": ["off"],
    "no-continue": ["off"],
    "no-inline-comments": ["off"],
    "no-invalid-this": ["off"],
    "no-multi-assign": ["off"],
    "no-negated-condition": ["off"],
    "no-nested-ternary": ["off"],
    "no-param-reassign": ["off"],
    "no-plusplus": ["off"],
    "no-restricted-imports": ["off"],
    "no-restricted-modules": ["off"],
    "no-restricted-syntax": ["off"],
    "no-ternary": ["off"],
    "no-undefined": ["off"],
    "no-underscore-dangle": ["off"],
    "no-useless-concat": ["off"],
    "object-curly-newline": ["off"],
    "one-var-declaration-per-line": ["off"],
    "padding-line-between-statements": ["off"],
    "prefer-arrow-callback": ["off"],
    "prefer-template": ["off"],
    "sort-imports": ["off"],
    "sort-keys": ["off"],
    "sort-vars": ["off"],

    "import/no-restricted-paths": ["off"],
    "import/no-internal-modules": ["off"],
    "import/no-cycle": ["off"],
    "import/no-relative-parent-imports": ["off"],
    "import/no-nodejs-modules": ["off"],
    "import/exports-last": ["off"],
    "import/no-namespace": ["off"],
    "import/prefer-default-export": ["off"],
    "import/max-dependencies": ["off"],
    "import/no-unassigned-import": ["off"],
    "import/no-default-export": ["off"],
    "import/no-named-export": ["off"],
    "import/group-exports": ["off"],
    "import/dynamic-import-chunkname": ["off"],

    "node/no-unpublished-import": ["off"],
    "node/no-unsupported-features/es-syntax": ["off"],

    "promise/no-native": ["off"],

    "jsdoc/no-undefined-types": ["off"],
    "jsdoc/newline-after-description": ["off"],
    "jsdoc/require-description": ["off"],
    "jsdoc/require-description-complete-sentence": ["off"],
    "jsdoc/require-example": ["off"],
    "jsdoc/require-hyphen-before-param-description": ["off"],
    "jsdoc/require-param-description": ["off"],
    "jsdoc/require-returns-check": ["off"],
    "jsdoc/require-returns-description": ["off"]
  }
};
